import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import { formatCurrency, formatPercent, formatPrice, formatSignedPrice } from '../utils/formatters';
import { translateCompanyStatus, translateOrderMode, translateOrderStatus, translateOrderType } from '../utils/labels';

type Company = { id:string; name:string; ticker:string; sector:string; description:string; initialPrice:string; currentPrice:string; availableOfferShares:number; totalShares:number; ownerSharePercent:string; publicOfferPercent:string; buyFeePercent:string; sellFeePercent:string; status:'ACTIVE'|'SUSPENDED'|'CLOSED'|'REJECTED'|'BANKRUPT'|'PENDING' };
type Holding={companyId:string;quantity:number};
type MarketOrder={id:string;companyId:string;type:'BUY'|'SELL';mode:'LIMIT'|'MARKET';quantity:number;remainingQuantity:number;limitPrice:string|null;status:'OPEN'|'PARTIALLY_FILLED'|'FILLED'|'CANCELED'|'REJECTED';createdAt:string};
type Trade={id:string;quantity:number;unitPrice:string;createdAt:string};
type DetailTab='preco'|'info'|'dados'; type MarketListTab='mercado'|'destaques'; type TradeFlow='buy'|'sell'|null; type BuyMode='initial'|'limit'|'market'; type SellMode='limit'|'market';

type InitialOfferBuyResponse = { priceBefore?: string | number; priceAfter?: string | number; priceIncrease?: string | number };

type ChartData={points:Array<{x:number;y:number;price:number;quantity:number}>;minPrice:number;maxPrice:number;initialPrice:number;currentPrice:number;variationAbsolute:number;variationPercent:number;lastPrice:number;note:string};
const timeframes=['Time','15m','1h','4h','1D','Mais','Profundidade']; const indicators=['MA','EMA','BOLL','VOL','MACD','RSI'];

function buildPriceTicks(min:number,max:number,count=5){ if(!Number.isFinite(min)||!Number.isFinite(max)) return []; if(min===max){const padding=Math.max(min*0.01,0.01);min-=padding;max+=padding;} const step=(max-min)/(count-1); return Array.from({length:count},(_,i)=>max-step*i); }
function getBookVolumeWeight(order:MarketOrder,maxVolume:number){ if(maxVolume<=0) return 0; return Math.max(8,Math.round((order.remainingQuantity/maxVolume)*100)); }
function getPriceChangePercent(company:Company){const initial=Number(company.initialPrice);const current=Number(company.currentPrice); if(!Number.isFinite(initial)||initial<=0||!Number.isFinite(current)) return 0; return ((current-initial)/initial)*100;}
function normalizeChartData(trades:Trade[],initialPrice:number,currentPrice:number):ChartData{ const ordered=[...trades].sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime()); const safeInitial=Number.isFinite(initialPrice)&&initialPrice>0?initialPrice:1; const safeCurrent=Number.isFinite(currentPrice)&&currentPrice>0?currentPrice:safeInitial; const seed=[{price:safeInitial,quantity:0},...ordered.map(t=>({price:Number(t.unitPrice),quantity:Number(t.quantity)||0})).filter(t=>Number.isFinite(t.price)&&t.price>0)]; if(seed[seed.length-1]?.price!==safeCurrent) seed.push({price:safeCurrent,quantity:0}); if(seed.length===1) seed.push(seed[0]); const prices=seed.map(s=>s.price); const minPrice=Math.min(...prices); const maxPrice=Math.max(...prices); const range=maxPrice-minPrice; const padding=Math.max((range||safeCurrent)*0.15,0.01); const chartMin=minPrice-padding; const chartMax=maxPrice+padding; const chartRange=chartMax-chartMin; const points=seed.map((p,index)=>({x:(index/(seed.length-1))*100,y:100-((p.price-chartMin)/chartRange)*100,price:p.price,quantity:p.quantity})); const variationAbsolute=safeCurrent-safeInitial; const variationPercent=(variationAbsolute/safeInitial)*100; return {points,minPrice,maxPrice,initialPrice:safeInitial,currentPrice:safeCurrent,variationAbsolute,variationPercent,lastPrice:seed[seed.length-1].price,note:trades.length===0?'Ainda sem trades. Exibindo preço inicial e atual.':'Gráfico baseado em trades reais e preço atual.'}; }

export function CompaniesPage(){
const [companies,setCompanies]=useState<Company[]>([]); const [selected,setSelected]=useState<Company|null>(null); const [walletBalance,setWalletBalance]=useState(0); const [holdingQty,setHoldingQty]=useState(0); const [book,setBook]=useState<{buyOrders:MarketOrder[];sellOrders:MarketOrder[]}>({buyOrders:[],sellOrders:[]}); const [myOrders,setMyOrders]=useState<MarketOrder[]>([]); const [trades,setTrades]=useState<Trade[]>([]);
const [activeTab,setActiveTab]=useState<DetailTab>('preco'); const [marketListTab,setMarketListTab]=useState<MarketListTab>('mercado'); const [tradeFlow,setTradeFlow]=useState<TradeFlow>(null); const [buyMode,setBuyMode]=useState<BuyMode>('initial'); const [sellMode,setSellMode]=useState<SellMode>('limit'); const [search,setSearch]=useState(''); const [activeIndicator,setActiveIndicator]=useState('VOL');
const [initialQty,setInitialQty]=useState(''); const [limitQty,setLimitQty]=useState(''); const [limitPrice,setLimitPrice]=useState(''); const [marketBuyQty,setMarketBuyQty]=useState(''); const [marketSellQty,setMarketSellQty]=useState(''); const [marketBuySlip,setMarketBuySlip]=useState('5'); const [marketSellSlip,setMarketSellSlip]=useState('5'); const [error,setError]=useState(''); const [message,setMessage]=useState('');
const loadCompanies=async()=>{const res=await api<{companies:Omit<Company,'description'>[]}>('/companies');setCompanies(res.companies.filter(c=>c.status==='ACTIVE').map(i=>({...i,description:''})));};
const loadWalletAndHolding=async(id?:string)=>{const res=await api<{wallet:{availableBalance:string};holdings:Holding[]}>('/me/holdings'); setWalletBalance(Number(res.wallet.availableBalance)); setHoldingQty(res.holdings.find(h=>h.companyId===id)?.quantity??0);};
const loadCompanyDetails=async(id:string)=>setSelected((await api<{company:Company}>(`/companies/${id}`)).company);
const loadMarket=async(id:string)=>{ const [orderBook,my,lastTrades]=await Promise.all([api<{buyOrders:MarketOrder[];sellOrders:MarketOrder[]}>(`/market/companies/${id}/order-book`),api<{orders:MarketOrder[]}>('/market/orders/me'),api<{trades:Trade[]}>(`/market/companies/${id}/trades`)]); setBook(orderBook); setMyOrders(my.orders.filter(o=>o.companyId===id)); setTrades(lastTrades.trades);};
const refreshSelected=async(id?:string)=>{if(!id)return; await Promise.all([loadCompanyDetails(id),loadWalletAndHolding(id),loadMarket(id),loadCompanies()]);};
useEffect(()=>{(async()=>{try{await loadCompanies();await loadWalletAndHolding();}catch(err){setError((err as Error).message);}})();},[]);
useEffect(()=>{if(!selected) return; loadMarket(selected.id).catch(err=>setError((err as Error).message));},[selected?.id]);

const buyInitialOffer=async(e:FormEvent)=>{e.preventDefault(); if(!selected) return; try{ await api<InitialOfferBuyResponse>(`/companies/${selected.id}/buy-initial-offer`,{method:'POST',body:JSON.stringify({quantity:Number(initialQty)})}); setInitialQty(''); setMessage('Compra realizada com sucesso.'); setError(''); await refreshSelected(selected.id);}catch(err){setError((err as Error).message);}};
const createLimitOrder=async(type:'BUY'|'SELL',e:FormEvent)=>{e.preventDefault(); if(!selected) return; try{ await api('/market/orders',{method:'POST',body:JSON.stringify({companyId:selected.id,type,mode:'LIMIT',quantity:Number(limitQty),limitPrice:Number(limitPrice)})}); setLimitQty(''); setLimitPrice(''); setMessage(type==='BUY'?'Ordem de compra criada.':'Ordem de venda criada.'); setError(''); await refreshSelected(selected.id);}catch(err){setError((err as Error).message);} };
const sendMarket=async(type:'BUY'|'SELL')=>{if(!selected) return; try{await api(`/market/companies/${selected.id}/${type==='BUY'?'buy-market':'sell-market'}`,{method:'POST',body:JSON.stringify({quantity:Number(type==='BUY'?marketBuyQty:marketSellQty),slippagePercent:Number(type==='BUY'?marketBuySlip:marketSellSlip)})}); if(type==='BUY')setMarketBuyQty(''); if(type==='SELL')setMarketSellQty(''); setMessage('Compra realizada com sucesso.'); setError(''); await refreshSelected(selected.id);}catch(err){setError((err as Error).message);}};
const cancelOrder=async(id:string)=>{if(!selected) return; try{await api(`/market/orders/${id}/cancel`,{method:'POST'}); setMessage('Ordem cancelada com sucesso.'); await refreshSelected(selected.id);}catch(err){setError((err as Error).message);} };

const buyFee=Number(selected?.buyFeePercent??'0'); const sellFee=Number(selected?.sellFeePercent??'0'); const limitSubtotal=(Number(limitQty)||0)*(Number(limitPrice)||0); const limitTotalBuy=limitSubtotal*(1+buyFee/100); const limitNetSell=limitSubtotal*(1-sellFee/100);
const bestAsk=useMemo(()=>book.sellOrders.length>0?Number(book.sellOrders[0].limitPrice??0):Number(selected?.currentPrice??0),[book.sellOrders,selected?.currentPrice]); const bestBid=useMemo(()=>book.buyOrders.length>0?Number(book.buyOrders[0].limitPrice??0):Number(selected?.currentPrice??0),[book.buyOrders,selected?.currentPrice]);
const maxBuyVolume=useMemo(()=>Math.max(0,...book.buyOrders.map(o=>o.remainingQuantity)),[book.buyOrders]); const maxSellVolume=useMemo(()=>Math.max(0,...book.sellOrders.map(o=>o.remainingQuantity)),[book.sellOrders]);
const chartData=useMemo(()=>normalizeChartData(trades,Number(selected?.initialPrice??1),Number(selected?.currentPrice??selected?.initialPrice??1)),[trades,selected?.currentPrice,selected?.initialPrice]);
const priceTicks=useMemo(()=>buildPriceTicks(chartData.minPrice,chartData.maxPrice),[chartData.minPrice,chartData.maxPrice]);
const visibleCompanies=useMemo(()=>companies.filter(c=>`${c.name} ${c.ticker}`.toLowerCase().includes(search.toLowerCase())),[companies,search]); const featuredCompanies=useMemo(()=>companies.slice(0,3),[companies]);
const totalBuyStrength=book.buyOrders.reduce((a,b)=>a+b.remainingQuantity,0); const totalSellStrength=book.sellOrders.reduce((a,b)=>a+b.remainingQuantity,0); const totalStrength=totalBuyStrength+totalSellStrength; const buyPercent=totalStrength===0?0:Math.round((totalBuyStrength/totalStrength)*100);
const totalTradeVolume=trades.reduce((sum,t)=>sum+Number(t.quantity||0),0);

if(!selected) return <section className='card market-page'><h2>🪙 Mercados</h2><input placeholder='Buscar token ou ticker' value={search} onChange={(e)=>setSearch(e.target.value)} /><nav className='quick-actions nested-card'><button className={marketListTab==='mercado'?'quick-pill active':'quick-pill'} onClick={()=>setMarketListTab('mercado')}>Mercado</button><button className={marketListTab==='destaques'?'quick-pill active':'quick-pill'} onClick={()=>setMarketListTab('destaques')}>Destaques</button></nav><ul className='company-list'>{(marketListTab==='destaques'?featuredCompanies.filter((c)=>`${c.name} ${c.ticker}`.toLowerCase().includes(search.toLowerCase())):visibleCompanies).map((company)=><li key={company.id} className='card company-visual-card finance-card'><p className='company-emoji'>🪙 {company.ticker}/RPC</p><strong>{company.name}</strong><p className='info-text'>Categoria: {company.sector} • Status: {translateCompanyStatus(company.status)}</p><p className='price-highlight'>{formatPrice(Number(company.currentPrice||company.initialPrice))} RPC</p><p className={getPriceChangePercent(company)>=0?'positive-change':'negative-change'}>{getPriceChangePercent(company)>=0?'▲':'▼'} {formatPercent(Math.abs(getPriceChangePercent(company)))}%</p><button className='button-primary' onClick={()=>refreshSelected(company.id)}>Negociar</button></li>)}</ul></section>;

return <section className='card market-page'><div className='trade-screen modern-market'><header className='card trade-header market-pair-header'><div className='market-pair-title'><button className='back-button' onClick={()=>setSelected(null)}>←</button><strong>{selected.ticker}/RPC ▾</strong><span>☆</span><span>🔔</span></div><div className='market-price-overview'><p className='trade-price-big'>{formatPrice(Number(selected.currentPrice))} RPC</p><p className={chartData.variationPercent>=0?'positive-change':'negative-change'}>{chartData.variationPercent>=0?'▲':'▼'} {formatPercent(Math.abs(chartData.variationPercent))}%</p></div><div className='market-stats-row'><span>Inicial: {formatPrice(Number(selected.initialPrice))}</span><span>Máx: {formatPrice(chartData.maxPrice)}</span><span>Mín: {formatPrice(chartData.minPrice)}</span><span>Volume: {totalTradeVolume>0?totalTradeVolume:'Sem negociações'}</span><span>Setor: {selected.sector}</span><span>Status: {translateCompanyStatus(selected.status)}</span></div></header>
{error&&<p className='status-message error'>{error}</p>}{message&&<p className='status-message success'>{message}</p>}
<nav className='market-top-tabs'><button className={activeTab==='preco'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('preco')}>Preço</button><button className={activeTab==='info'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('info')}>Informações</button><button className={activeTab==='dados'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('dados')}>Dados de trading</button></nav>
{activeTab==='preco'&&<><section className='card nested-card'><div className='chart-timeframes'>{timeframes.map((t)=><button key={t} className='quick-pill'>{t}</button>)}</div><div className='modern-chart-shell'><svg viewBox='0 0 115 100' preserveAspectRatio='none' className='line-chart'><polyline points={chartData.points.map((p)=>`${p.x},${p.y}`).join(' ')} fill='none' stroke='#60a5fa' strokeWidth='1.5'/><polygon points={`0,100 ${chartData.points.map((p)=>`${p.x},${p.y}`).join(' ')} 100,100`} fill='rgba(96,165,250,.16)'/><line x1='0' x2='100' y1={chartData.points[chartData.points.length-1].y} y2={chartData.points[chartData.points.length-1].y} className='current-price-line'/><circle cx={chartData.points[chartData.points.length-1].x} cy={chartData.points[chartData.points.length-1].y} r='1.4' fill='#f8fafc'/>{priceTicks.map((tick)=><text key={tick} x='102' y={100-((tick-(chartData.minPrice-Math.max((chartData.maxPrice-chartData.minPrice)*0.15,0.01)))/((chartData.maxPrice+Math.max((chartData.maxPrice-chartData.minPrice)*0.15,0.01))-(chartData.minPrice-Math.max((chartData.maxPrice-chartData.minPrice)*0.15,0.01))))*100} className='price-scale-label'>{formatPrice(tick)}</text>)}<rect x='101' y={chartData.points[chartData.points.length-1].y-3} width='14' height='6' rx='1.5' className='current-price-badge'/><text x='108' y={chartData.points[chartData.points.length-1].y+1.3} textAnchor='middle' fontSize='2.2' fill='#0f172a'>{formatPrice(chartData.currentPrice)}</text></svg></div><div className='chart-meta'><div><span>Mínimo</span><strong>{formatPrice(chartData.minPrice)}</strong></div><div><span>Máximo</span><strong>{formatPrice(chartData.maxPrice)}</strong></div><div><span>Atual</span><strong>{formatPrice(chartData.currentPrice)}</strong></div></div><p className='info-text'>Legenda MA: média simples visual baseada na série atual.</p>
<div className='volume-mini-chart'>{trades.length===0?<p className='empty-state'>Sem volume de negociações ainda.</p>:<div className='volume-bars'>{chartData.points.slice(1).map((p,i)=><div key={i} style={{height:`${Math.max(6,(p.quantity/Math.max(...chartData.points.map(pp=>pp.quantity||1)))*60)}px`}} />)}</div>}</div><div className='indicator-tabs'>{indicators.map((ind)=><button key={ind} className={activeIndicator===ind?'quick-pill active':'quick-pill'} onClick={()=>setActiveIndicator(ind)}>{ind}</button>)}</div></section>
<section className='card nested-card'><div className='book-strength-bar'><div className='book-strength-buy' style={{width:`${buyPercent}%`}}>Compradores {buyPercent}%</div><div className='book-strength-sell' style={{width:`${100-buyPercent}%`}}>Vendedores {100-buyPercent}%</div></div><div className='summary-grid order-book-grid'><div className='summary-item buy-side'><strong>Oferta/Quantidade • Preço</strong>{book.buyOrders.length===0?<p className='empty-state'>Sem ordens de compra.</p>:book.buyOrders.map((order)=><div key={order.id} className='order-book-row'><div className='order-book-bar buy' style={{width:`${getBookVolumeWeight(order,maxBuyVolume)}%`}}/><p>Qtd {order.remainingQuantity} • {formatPrice(Number(order.limitPrice??0))} • Total {formatCurrency(Number(order.limitPrice??0)*order.remainingQuantity)}</p></div>)}</div><div className='summary-item sell-side'><strong>Oferta/Quantidade • Preço</strong>{book.sellOrders.length===0?<p className='empty-state'>Sem ordens de venda.</p>:book.sellOrders.map((order)=><div key={order.id} className='order-book-row'><div className='order-book-bar sell' style={{width:`${getBookVolumeWeight(order,maxSellVolume)}%`}}/><p>Qtd {order.remainingQuantity} • {formatPrice(Number(order.limitPrice??0))} • Total {formatCurrency(Number(order.limitPrice??0)*order.remainingQuantity)}</p></div>)}</div></div></section>
<div className='chart-action-bar'><button className='button-success' onClick={()=>{setTradeFlow('buy');setBuyMode('initial');}}>Comprar</button><button className='button-danger' onClick={()=>{setTradeFlow('sell');setSellMode('limit');}}>Vender</button></div></>}
{activeTab==='info'&&<section className='card nested-card'><h4>Informações</h4><p>{selected.description||'Projeto/token listado para negociação em ambiente RP.'}</p><p>Oferta disponível: {selected.availableOfferShares}</p><p>Total de tokens: {selected.totalShares}</p></section>}
{activeTab==='dados'&&<section className='card nested-card'><h4>Dados de trading</h4><p>Taxa compra: {buyFee}%</p><p>Taxa venda: {sellFee}%</p><p>Supply: {selected.totalShares}</p><p>Oferta disponível: {selected.availableOfferShares}</p><p>Market cap fictício: {formatCurrency(Number(selected.currentPrice)*selected.totalShares)}</p><p>Spread atual: {formatSignedPrice(bestAsk-bestBid)}</p></section>}

{tradeFlow&&<div className='trade-panel-backdrop' onClick={()=>setTradeFlow(null)}><section className='trade-bottom-sheet' onClick={(e)=>e.stopPropagation()}><div className='trade-panel-header'><h4>{tradeFlow==='buy'?'Comprar':'Vender'}</h4><button className='back-button' onClick={()=>setTradeFlow(null)}>Fechar</button></div>{tradeFlow==='buy'&&<><nav className='quick-actions'><button className={buyMode==='initial'?'quick-pill active':'quick-pill'} onClick={()=>setBuyMode('initial')}>Lançamento</button><button className={buyMode==='limit'?'quick-pill active':'quick-pill'} onClick={()=>setBuyMode('limit')}>Limite</button><button className={buyMode==='market'?'quick-pill active':'quick-pill'} onClick={()=>setBuyMode('market')}>Mercado</button></nav>{buyMode==='initial'&&<form onSubmit={buyInitialOffer}><input type='number' min='1' required value={initialQty} onChange={(e)=>setInitialQty(e.target.value)} placeholder='Quantidade'/><p className='info-text'>Saldo disponível: {formatCurrency(walletBalance)} RPC</p><button className='button-success' type='submit'>Comprar no lançamento</button></form>}{buyMode==='limit'&&<form onSubmit={(e)=>createLimitOrder('BUY',e)}><input type='number' min='1' required value={limitQty} onChange={(e)=>setLimitQty(e.target.value)} placeholder='Quantidade'/><input type='number' min='0.01' step='0.01' required value={limitPrice} onChange={(e)=>setLimitPrice(e.target.value)} placeholder='Preço limite'/><p>Taxa estimada: {buyFee}% • Total estimado: {formatCurrency(limitTotalBuy)}</p><button className='button-success' type='submit'>Enviar ordem de compra</button></form>}{buyMode==='market'&&<div><input type='number' min='1' value={marketBuyQty} onChange={(e)=>setMarketBuyQty(e.target.value)} placeholder='Quantidade'/><input type='number' min='0' max='100' value={marketBuySlip} onChange={(e)=>setMarketBuySlip(e.target.value)} placeholder='Slippage (%)'/><p>Preço atual: {formatPrice(bestAsk)}</p><button className='button-success' onClick={()=>sendMarket('BUY')}>Comprar mercado</button></div>}</>}
{tradeFlow==='sell'&&<><nav className='quick-actions'><button className={sellMode==='limit'?'quick-pill active':'quick-pill'} onClick={()=>setSellMode('limit')}>Limite</button><button className={sellMode==='market'?'quick-pill active':'quick-pill'} onClick={()=>setSellMode('market')}>Mercado</button></nav>{sellMode==='limit'&&<form onSubmit={(e)=>createLimitOrder('SELL',e)}><input type='number' min='1' required value={limitQty} onChange={(e)=>setLimitQty(e.target.value)} placeholder='Quantidade'/><input type='number' min='0.01' step='0.01' required value={limitPrice} onChange={(e)=>setLimitPrice(e.target.value)} placeholder='Preço limite'/><p>Taxa estimada: {sellFee}% • Total líquido estimado: {formatCurrency(limitNetSell)}</p><button className='button-danger' type='submit'>Enviar ordem de venda</button></form>}{sellMode==='market'&&<div><input type='number' min='1' value={marketSellQty} onChange={(e)=>setMarketSellQty(e.target.value)} placeholder='Quantidade'/><input type='number' min='0' max='100' value={marketSellSlip} onChange={(e)=>setMarketSellSlip(e.target.value)} placeholder='Slippage (%)'/><p>Tokens em carteira: {holdingQty}</p><button className='button-danger' onClick={()=>sendMarket('SELL')}>Vender mercado</button></div>}</>}</section></div>}

<section className='card nested-card'><h4>Minhas ordens</h4>{myOrders.length===0&&<p className='empty-state'>Você ainda não possui ordens neste mercado.</p>}<div className='mobile-card-list'>{myOrders.map((order)=><article key={order.id} className='summary-item compact-card'><p><strong>{translateOrderType(order.type)}</strong> · {translateOrderMode(order.mode)}</p><p>Quantidade: {order.quantity} · Restante: {order.remainingQuantity}</p><p>Status: {translateOrderStatus(order.status)}</p><p>Preço: {order.limitPrice?formatPrice(Number(order.limitPrice)):'Agora'}</p>{(order.status==='OPEN'||order.status==='PARTIALLY_FILLED')&&order.mode==='LIMIT'&&<button className='button-danger' onClick={()=>cancelOrder(order.id)}>Cancelar ordem</button>}</article>)}</div></section>
</div></section>;
}
