import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api } from '../services/api';
import { formatCurrency, formatPercent, formatPrice, formatSignedPrice } from '../utils/formatters';
import { translateCompanyStatus, translateOrderMode, translateOrderStatus, translateOrderType } from '../utils/labels';

type Company = { id:string; name:string; ticker:string; sector:string; description:string; initialPrice:string; currentPrice:string; availableOfferShares:number; totalShares:number; ownerSharePercent:string; publicOfferPercent:string; buyFeePercent:string; sellFeePercent:string; status:'ACTIVE'|'SUSPENDED'|'CLOSED'|'REJECTED'|'BANKRUPT'|'PENDING' };
type Holding = { companyId: string; quantity: number };
type MarketOrder = { id:string; companyId:string; type:'BUY'|'SELL'; mode:'LIMIT'|'MARKET'; quantity:number; remainingQuantity:number; limitPrice:string|null; status:'OPEN'|'PARTIALLY_FILLED'|'FILLED'|'CANCELED'|'REJECTED'; createdAt:string };
type Trade = { id:string; quantity:number; unitPrice:string; createdAt:string };
type DetailTab = 'resumo'|'grafico'|'livro'|'ordens'|'historico';
type BuyMode = 'initial'|'limit'|'market'; type SellMode='limit'|'market';

type ChartData = { points:Array<{x:number;y:number;price:number}>; minPrice:number; maxPrice:number; initialPrice:number; currentPrice:number; variationAbsolute:number; variationPercent:number; lastPrice:number; note:string; hasEnoughHistory:boolean };

function normalizeChartData(trades: Trade[], initialPrice:number, currentPrice:number): ChartData {
  const prices = [...trades].sort((a,b)=>new Date(a.createdAt).getTime()-new Date(b.createdAt).getTime()).map(t=>Number(t.unitPrice)).filter(p=>Number.isFinite(p)&&p>0);
  const safeInitial = Number.isFinite(initialPrice) && initialPrice>0 ? initialPrice : 1;
  const safeCurrent = Number.isFinite(currentPrice) && currentPrice>0 ? currentPrice : safeInitial;
  const series = [safeInitial, ...prices, safeCurrent];
  const minPrice = Math.min(...series); const maxPrice = Math.max(...series);
  const rawRange = maxPrice - minPrice;
  const minimalPadding = Math.max(safeCurrent * 0.01, 0.01);
  const padding = rawRange === 0 ? minimalPadding : Math.max(rawRange * 0.2, minimalPadding);
  const chartMin = minPrice - padding; const chartMax = maxPrice + padding; const range = chartMax - chartMin;
  const points = series.map((price, i)=>({ x: series.length===1?50:(i/(series.length-1))*100, y: 100-((price-chartMin)/range)*100, price }));
  return { points, minPrice, maxPrice, initialPrice:safeInitial, currentPrice:safeCurrent, variationAbsolute:safeCurrent-safeInitial, variationPercent:((safeCurrent-safeInitial)/safeInitial)*100, lastPrice:safeCurrent, note: trades.length<2 ? 'Histórico insuficiente para formar gráfico completo.' : 'Variação baseada em preços reais de lançamento e negociações.', hasEnoughHistory: trades.length>=2 };
}

export function CompaniesPage() {
  const [companies,setCompanies]=useState<Company[]>([]); const [selected,setSelected]=useState<Company|null>(null); const [walletBalance,setWalletBalance]=useState(0); const [holdingQty,setHoldingQty]=useState(0);
  const [book,setBook]=useState<{buyOrders:MarketOrder[];sellOrders:MarketOrder[]}>({buyOrders:[],sellOrders:[]}); const [myOrders,setMyOrders]=useState<MarketOrder[]>([]); const [trades,setTrades]=useState<Trade[]>([]);
  const [activeTab,setActiveTab]=useState<DetailTab>('grafico'); const [search,setSearch]=useState(''); const [buyMode,setBuyMode]=useState<BuyMode>('initial'); const [sellMode,setSellMode]=useState<SellMode>('limit');
  const [initialQty,setInitialQty]=useState(''); const [limitQty,setLimitQty]=useState(''); const [limitPrice,setLimitPrice]=useState(''); const [marketBuyQty,setMarketBuyQty]=useState(''); const [marketSellQty,setMarketSellQty]=useState(''); const [marketBuySlip,setMarketBuySlip]=useState('5'); const [marketSellSlip,setMarketSellSlip]=useState('5'); const [error,setError]=useState(''); const [message,setMessage]=useState('');

  async function loadCompanies(){ const r=await api<{companies:Omit<Company,'description'>[]}>('/companies'); setCompanies(r.companies.filter(c=>c.status==='ACTIVE').map(c=>({...c,description:''}))); }
  async function loadWalletAndHolding(companyId?:string){ const r=await api<{wallet:{availableBalance:string};holdings:Holding[]}>('/me/holdings'); setWalletBalance(Number(r.wallet.availableBalance)); setHoldingQty(r.holdings.find(h=>h.companyId===companyId)?.quantity??0); }
  async function loadCompanyDetails(companyId:string){ const r=await api<{company:Company}>(`/companies/${companyId}`); setSelected(r.company); }
  async function loadMarket(companyId:string){ const [ob,my,last]=await Promise.all([api<{buyOrders:MarketOrder[];sellOrders:MarketOrder[]}>(`/market/companies/${companyId}/order-book`),api<{orders:MarketOrder[]}>('/market/orders/me'),api<{trades:Trade[]}>(`/market/companies/${companyId}/trades`)]); setBook({ buyOrders:[...ob.buyOrders].sort((a,b)=>Number(b.limitPrice??0)-Number(a.limitPrice??0)), sellOrders:[...ob.sellOrders].sort((a,b)=>Number(a.limitPrice??0)-Number(b.limitPrice??0)) }); setMyOrders(my.orders.filter(o=>o.companyId===companyId)); setTrades(last.trades); }

  useEffect(()=>{loadCompanies().then(()=>loadWalletAndHolding()).catch((e:Error)=>setError(e.message));},[]);
  useEffect(()=>{if(selected) loadMarket(selected.id).catch((e:Error)=>setError(e.message));},[selected?.id]);
  async function selectCompany(id:string){ setError(''); setMessage(''); await Promise.all([loadCompanyDetails(id), loadWalletAndHolding(id)]); }

  async function buyInitialOffer(event:FormEvent){ event.preventDefault(); if(!selected) return; await api(`/companies/${selected.id}/buy-initial-offer`,{method:'POST',body:JSON.stringify({quantity:Number(initialQty)})}); setInitialQty(''); setMessage('Compra no lançamento realizada com sucesso.'); await Promise.all([loadCompanyDetails(selected.id),loadWalletAndHolding(selected.id),loadCompanies(),loadMarket(selected.id)]); }
  async function createLimitOrder(type:'BUY'|'SELL', event:FormEvent){ event.preventDefault(); if(!selected) return; await api('/market/orders',{method:'POST',body:JSON.stringify({companyId:selected.id,type,mode:'LIMIT',quantity:Number(limitQty),limitPrice:Number(limitPrice)})}); setLimitQty(''); setLimitPrice(''); setMessage(type==='BUY'?'Ordem de compra criada.':'Ordem de venda criada.'); await Promise.all([loadCompanyDetails(selected.id),loadWalletAndHolding(selected.id),loadMarket(selected.id)]); }
  async function sendMarket(type:'BUY'|'SELL'){ if(!selected) return; await api(`/market/companies/${selected.id}/${type==='BUY'?'buy-market':'sell-market'}`,{method:'POST',body:JSON.stringify({quantity:Number(type==='BUY'?marketBuyQty:marketSellQty),slippagePercent:Number(type==='BUY'?marketBuySlip:marketSellSlip)})}); setMessage(type==='BUY'?'Compra a mercado enviada.':'Venda a mercado enviada.'); await Promise.all([loadCompanyDetails(selected.id),loadWalletAndHolding(selected.id),loadMarket(selected.id)]); }
  async function cancelOrder(orderId:string){ if(!selected) return; await api(`/market/orders/${orderId}/cancel`,{method:'POST'}); setMessage('Ordem cancelada com sucesso.'); await loadMarket(selected.id); }

  const chartData=useMemo(()=>normalizeChartData(trades,Number(selected?.initialPrice??1),Number(selected?.currentPrice??1)),[trades,selected?.initialPrice,selected?.currentPrice]);
  const buyFee=Number(selected?.buyFeePercent??0), sellFee=Number(selected?.sellFeePercent??0), limitSubtotal=(Number(limitQty)||0)*(Number(limitPrice)||0);
  const limitTotalBuy=limitSubtotal*(1+buyFee/100), limitNetSell=limitSubtotal*(1-sellFee/100);

  if(!selected) return <section className="card market-page"><h2>🪙 Mercado</h2><input placeholder="Buscar projeto ou ticker" value={search} onChange={e=>setSearch(e.target.value)} />{error&&<p className="status-message error">{error}</p>}<ul className="company-list nested-card">{companies.filter(c=>`${c.name} ${c.ticker}`.toLowerCase().includes(search.toLowerCase())).map((c)=><li key={c.id} className="card company-visual-card finance-card"><strong>{c.ticker}/RPC</strong><p>{c.name}</p><p className="info-text">Setor: {c.sector}</p><p className="price-highlight">Preço: {formatPrice(Number(c.currentPrice))} RPC</p><button className="button-primary" onClick={()=>selectCompany(c.id)}>Abrir mercado</button></li>)}</ul></section>;

  return <section className="card market-page"><div className="trade-screen modern-market">{error&&<p className="status-message error">{error}</p>}{message&&<p className="status-message success">{message}</p>}
  <header className="card trade-header market-token-header"><button className="back-button" onClick={()=>setSelected(null)}>← Mercados</button><h3>{selected.ticker}/RPC</h3><p>{selected.name} • {selected.sector} • {translateCompanyStatus(selected.status)}</p><p className="trade-price-big">{formatPrice(Number(selected.currentPrice))} RPC</p><p className={chartData.variationPercent>=0?'positive-change':'negative-change'}>{chartData.variationPercent>=0?'▲':'▼'} {formatPercent(Math.abs(chartData.variationPercent))}%</p><div className="summary-grid"><div className="summary-item"><span className="summary-label">Oferta disponível</span><strong className="summary-value">{selected.availableOfferShares.toLocaleString('pt-BR')}</strong></div><div className="summary-item"><span className="summary-label">Minhas posições</span><strong className="summary-value">{holdingQty}</strong></div><div className="summary-item"><span className="summary-label">Saldo disponível</span><strong className="summary-value">{formatCurrency(walletBalance)} RPC</strong></div></div></header>
  <section className="summary-grid nested-card market-kpis"><div className="summary-item"><span className="summary-label">Preço inicial</span><strong>{formatPrice(Number(selected.initialPrice))}</strong></div><div className="summary-item"><span className="summary-label">Market cap fictício</span><strong>{formatCurrency(Number(selected.currentPrice)*selected.totalShares)} RPC</strong></div><div className="summary-item"><span className="summary-label">Taxa de compra</span><strong>{buyFee}%</strong></div><div className="summary-item"><span className="summary-label">Taxa de venda</span><strong>{sellFee}%</strong></div></section>
  <nav className="quick-actions nested-card"><button className={activeTab==='grafico'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('grafico')}>Gráfico</button><button className={activeTab==='livro'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('livro')}>Livro de ofertas</button><button className={activeTab==='resumo'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('resumo')}>Comprar e vender</button><button className={activeTab==='ordens'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('ordens')}>Minhas ordens</button><button className={activeTab==='historico'?'quick-pill active':'quick-pill'} onClick={()=>setActiveTab('historico')}>Negociações</button></nav>
  {activeTab==='grafico' && <section className="card nested-card"><h4>Gráfico de preço</h4><div className="chart-wrap chart-wrap-highlight"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="line-chart"><polyline points={chartData.points.map(p=>`${p.x},${p.y}`).join(' ')} fill="none" stroke="#22d3ee" strokeWidth="2.4" vectorEffect="non-scaling-stroke" /></svg></div><div className="chart-meta"><div><span>Mínimo</span><strong>{formatPrice(chartData.minPrice)}</strong></div><div><span>Máximo</span><strong>{formatPrice(chartData.maxPrice)}</strong></div><div><span>Atual</span><strong>{formatPrice(chartData.currentPrice)}</strong></div></div><p className="info-text">{chartData.note}</p></section>}
  {activeTab==='livro' && <section className="card nested-card order-book-grid"><div className="summary-item buy-side"><strong>Compras</strong>{book.buyOrders.length===0?<p className="empty-state">Sem ordens de compra.</p>:book.buyOrders.map(o=>{const p=Number(o.limitPrice??0);const total=p*o.remainingQuantity;return <p key={o.id}>{formatPrice(p)} • {o.remainingQuantity} • {formatCurrency(total)}</p>;})}</div><div className="summary-item sell-side"><strong>Vendas</strong>{book.sellOrders.length===0?<p className="empty-state">Sem ordens de venda.</p>:book.sellOrders.map(o=>{const p=Number(o.limitPrice??0);const total=p*o.remainingQuantity;return <p key={o.id}>{formatPrice(p)} • {o.remainingQuantity} • {formatCurrency(total)}</p>;})}</div></section>}
  {activeTab==='resumo' && <section className="card nested-card"><h4>Comprar e vender</h4><nav className="quick-actions"><button className={buyMode==='initial'?'quick-pill active':'quick-pill'} onClick={()=>setBuyMode('initial')}>Lançamento inicial</button><button className={buyMode==='limit'?'quick-pill active':'quick-pill'} onClick={()=>setBuyMode('limit')}>Comprar limite</button><button className={buyMode==='market'?'quick-pill active':'quick-pill'} onClick={()=>setBuyMode('market')}>Comprar mercado</button><button className={sellMode==='limit'?'quick-pill active':'quick-pill'} onClick={()=>setSellMode('limit')}>Vender limite</button><button className={sellMode==='market'?'quick-pill active':'quick-pill'} onClick={()=>setSellMode('market')}>Vender mercado</button></nav>{buyMode==='initial'&&selected.availableOfferShares>0&&<form onSubmit={buyInitialOffer}><input type="number" min="1" required value={initialQty} onChange={e=>setInitialQty(e.target.value)} placeholder="Quantidade"/><button className="button-success">Comprar no lançamento</button></form>}
  {buyMode==='limit'&&<form onSubmit={(e)=>createLimitOrder('BUY',e)}><input type="number" min="1" required value={limitQty} onChange={e=>setLimitQty(e.target.value)} placeholder="Quantidade"/><input type="number" min="0.01" step="0.01" required value={limitPrice} onChange={e=>setLimitPrice(e.target.value)} placeholder="Preço limite"/><p className="info-text">Total estimado: {formatCurrency(limitTotalBuy)} RPC • Taxa: {buyFee}%</p><button className="button-success">Comprar</button></form>}
  {buyMode==='market'&&<div><input type="number" min="1" value={marketBuyQty} onChange={e=>setMarketBuyQty(e.target.value)} placeholder="Quantidade"/><input type="number" min="0" max="100" value={marketBuySlip} onChange={e=>setMarketBuySlip(e.target.value)} placeholder="Slippage (%)"/><button className="button-success" onClick={()=>sendMarket('BUY')}>Comprar</button></div>}
  {sellMode==='limit'&&<form onSubmit={(e)=>createLimitOrder('SELL',e)}><input type="number" min="1" required value={limitQty} onChange={e=>setLimitQty(e.target.value)} placeholder="Quantidade"/><input type="number" min="0.01" step="0.01" required value={limitPrice} onChange={e=>setLimitPrice(e.target.value)} placeholder="Preço limite"/><p className="info-text">Total líquido estimado: {formatCurrency(limitNetSell)} RPC • Taxa: {sellFee}%</p><button className="button-danger">Vender</button></form>}
  {sellMode==='market'&&<div><input type="number" min="1" value={marketSellQty} onChange={e=>setMarketSellQty(e.target.value)} placeholder="Quantidade"/><input type="number" min="0" max="100" value={marketSellSlip} onChange={e=>setMarketSellSlip(e.target.value)} placeholder="Slippage (%)"/><button className="button-danger" onClick={()=>sendMarket('SELL')}>Vender</button></div>}</section>}
  {activeTab==='ordens' && <section className="card nested-card"><h4>Minhas ordens</h4>{myOrders.length===0?<p className="empty-state">Você não possui ordens neste ativo.</p>:myOrders.map(o=><article key={o.id} className="summary-item"><p>{translateOrderType(o.type)} • {translateOrderMode(o.mode)} • {translateOrderStatus(o.status)}</p><p>Qtd: {o.quantity} | Restante: {o.remainingQuantity}</p>{(o.status==='OPEN'||o.status==='PARTIALLY_FILLED')&&o.mode==='LIMIT'&&<button className="button-danger" onClick={()=>cancelOrder(o.id)}>Cancelar ordem</button>}</article>)}</section>}
  {activeTab==='historico' && <section className="card nested-card"><h4>Negociações recentes</h4>{trades.length===0?<p className="empty-state">Sem negociações recentes.</p>:trades.map(t=><article key={t.id} className="summary-item"><p>Preço: {formatPrice(Number(t.unitPrice))}</p><p>Quantidade: {t.quantity}</p><p>{new Date(t.createdAt).toLocaleString('pt-BR')}</p></article>)}</section>}
  </div></section>;
}
