export const RPC_MARKET_MAX_OPEN_ORDERS_PER_USER = 20;
export const COMPANY_MARKET_MAX_OPEN_ORDERS_PER_USER = 30;
export const MAX_ORDER_CANCELS_PER_MINUTE = 10;
export const MAX_RPC_TRADES_PER_MINUTE = 20;
export const MAX_COMPANY_TRADES_PER_MINUTE = 20;
export const MAX_REPORTS_PER_HOUR = 5;
export const MAX_PENDING_WITHDRAWALS_PER_USER = 3;
export const MAX_PROJECT_CREATIONS_PER_DAY = 3;
